--1
SELECT SUBJ_ID FROM exam_marks
WHERE EXAM_DATE BETWEEN '10/01/1999' AND '20/01/1999';
--2
SELECT * FROM subject
WHERE SUBJ_ID IN (
    SELECT DISTINCT SUBJ_ID FROM exam_marks
    WHERE STUDENT_ID IN (12, 32)
);
--3
SELECT SUBJ_NAME FROM subject
WHERE SUBJ_NAME LIKE 'И%';

--4
SELECT * FROM student
WHERE NAME GLOB '[ИС]*';

--5
SELECT * FROM exam_marks
WHERE MARK IS NULL;

--6
SELECT * FROM exam_marks
WHERE MARK IS NOT NULL;