--1
SELECT * FROM subject;

--2
SELECT * FROM exam_marks
WHERE SUBJ_ID = 12;

--3
SELECT KURS, SURNAME, NAME, STIPEND FROM student;

--4
SELECT SUBJ_NAME, HOUR FROM subject
WHERE SEMESTER = 4;

--5
SELECT DISTINCT MARK FROM exam_marks;

--6
SELECT SURNAME FROM student
WHERE KURS >= 3;

--7
SELECT SURNAME, NAME, KURS FROM student
WHERE STIPEND > 140;

--8
SELECT SUBJ_NAME FROM subject
WHERE HOUR > 30;

--9
SELECT * FROM university
WHERE RATING > 300;

--10
SELECT SURNAME, NAME, KURS FROM student
WHERE STIPEND >= 100 AND CITY = 'Воронеж';

--11
SELECT *
FROM STUDENT
WHERE (STIPEND < 100 OR
 NOT (BIRTHDAY >= '10/03/1980'
 AND STUDENT_ID > 1003 ));

--12
SELECT *
FROM STUDENT
WHERE NOT ((BIRTHDAY = '10/03/1980' OR STIPEND > 100)
 AND STUDENT_ID >= 1003 );